# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اﻷسم اﻷنجليزي')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='اﻷسم العربي')),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('is_new', models.BooleanField(default=False)),
                ('stampdate', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
