# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mattress', verbose_name='صوره المرتبه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product', verbose_name='صوره المنتج'),
            preserve_default=False,
        ),
    ]
