# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=300)),
                ('stampdate', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('cover', models.ImageField(upload_to='product')),
                ('is_new', models.BooleanField(default=False)),
                ('stampdate', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mattress',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mattress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mattress',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='features',
            field=models.TextField(verbose_name='المميزات'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='إظهار في الصفحه الرئيسيه'),
        ),
    ]
