# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'منتج مستلزمات تصنيع', 'verbose_name_plural': 'مستلزمات التصنيع'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='text',
            field=models.CharField(max_length=200, unique=True, verbose_name='أسم المنتج'),
        ),
    ]
