# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171010_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'جهه اﻷتصال', 'verbose_name_plural': 'جهات اﻷتصال'},
        ),
        migrations.AlterModelOptions(
            name='mattress',
            options={'verbose_name': 'المرتبه', 'verbose_name_plural': 'المراتب'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.RenameField(
            model_name='mattress',
            old_name='verbose_name',
            new_name='v_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='verbose_name',
        ),
        migrations.AddField(
            model_name='products',
            name='v_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='اﻷسم العربي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=30, verbose_name='أسم جهه اﻷتصال'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='value',
            field=models.CharField(max_length=300, verbose_name='جهه التصال'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='cover',
            field=models.ImageField(upload_to='mattress', verbose_name='صوره المرتبه'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=models.ImageField(upload_to='product', verbose_name='صوره المنتج'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='products',
            name='features',
            field=models.TextField(verbose_name='المميزات'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='إظهار في الصفحه الرئيسيه'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اﻷسم اﻷنجليزي'),
        ),
    ]
