# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171104_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='facebook',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='رابط صفحه الفيس بوك'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='رابط صفحه الإنستجرام'),
            preserve_default=False,
        ),
    ]
