# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20171010_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mattress',
            name='v_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='v_name',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='stampdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اﻷسم العربي'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='stampdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اﻷسم العربي'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stampdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
