# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20171019_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_word', models.TextField(verbose_name='كلمه عن الشركه')),
            ],
        ),
        migrations.CreateModel(
            name='Telephones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='اﻷسم')),
                ('number', models.IntegerField(verbose_name='رقم الهاتفذ')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phones',
            field=models.ManyToManyField(to='public.Telephones'),
        ),
    ]
