# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20171028_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'البيانات العامه', 'verbose_name_plural': 'البينات العامه'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='phones',
        ),
        migrations.DeleteModel(
            name='Telephones',
        ),
    ]
