# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20171028_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='اﻷسم')),
                ('adress', models.TextField(verbose_name='العنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='اﻷسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد اﻷلكتروني')),
            ],
        ),
        migrations.CreateModel(
            name='Telephones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='اﻷسم')),
                ('number', models.IntegerField(verbose_name='رقم الهاتف')),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'البيانات العامه', 'verbose_name_plural': 'البيانات العامه'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='adresses',
            field=models.ManyToManyField(to='public.Adresses'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='emails',
            field=models.ManyToManyField(to='public.Emails'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='telephones',
            field=models.ManyToManyField(to='public.Telephones'),
        ),
    ]
