# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20171028_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresses',
            options={'verbose_name': 'العنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'البريد اﻷلكتروني', 'verbose_name_plural': 'البريد اﻷلكتروني'},
        ),
        migrations.AlterModelOptions(
            name='telephones',
            options={'verbose_name': 'الهاتف', 'verbose_name_plural': 'ارقام التلفون'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='adresses',
            field=models.ManyToManyField(to='public.Adresses', verbose_name='العناوين'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='emails',
            field=models.ManyToManyField(to='public.Emails', verbose_name='البريد اﻷلكتروني'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='telephones',
            field=models.ManyToManyField(to='public.Telephones', verbose_name='الهواتف'),
        ),
    ]
