# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 10:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20171028_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephones',
            name='number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='لابد ان يكون رقم هاتف حقيقي', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
